[package]
name = "mouse-barrier"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
winapi.workspace = true
tracing = { workspace = true }